hostname: HOSTNAME
backup:
  - /path/one
  - /path/two

api:
  root: http://api.url
  client-id: AUTH0_CLIENT_ID
  client-secret: AUTH0_CLIENT_SECRET
  audience: https://AUTH0_AUDIENCE
  token-url: https://AUTH0_TOKEN_URL

restic:
  binary: /path/to/restic
  repository: RESTIC_REPOSITORY
  password: RESTIC_PASSWORD
  google-project-id: GOOGLE_PROJECT_ID
  google-credentials: GOOGLE_APPLICATION_CREDENTIALS
